### ISSUE TITLE
1-setup-containers.sh appears to be dependent on cli_1 container which has been deprecated

### ISSUE THREAD

**Issue by secpg** [conjurdemos/cdemo#13]
I have setup a cdemo environment on an AWS hosted CentOS 7 machine and the output of ./1-setup-containers.sh with 2 numerical arguments (2 5)is as follows; ERROR: No container found for cli_1

There is no cli_1 container deployed by running  _install-dependencies.sh and 0-startup-conjur.sh. It is my understanding the containerized cli has been deprecated. I am using  conjur-appliance-4.9.9.1.tar and pointed the 0-startup-conjur.sh script to its location prior to running. 

Perhaps there is a workaround I am not aware of. 

Thanks in advance.

**Comment by jodyhuntatx** [comment]
The cli container should have been started by 0-startup-conjur.sh. The CLI container is mostly referred to using its docker-compose service name  in 1-setup-containers.sh  (docker-compose exec -T cli ...). But it does need to use its container name when copying the API key to the shared data volume. Maybe that works differently in AWS for some reason. Send me an email and we can setup a debug session on Monday: jody.hunt@cyberark.com

**Comment by secpg** [comment]
Thanks Jody. I will reach out.

**Comment by jodyhuntatx** [comment]
resolved by re-running 0-startup...
