### ISSUE TITLE
Combine RUN command in Dockerfile

### ISSUE THREAD

**Issue by infamousjoeg** [conjurdemos/cdemo#15]
https://github.com/conjurdemos/cdemo/blob/78c34ca280a71bd0223831d7b81c9eb25ed78ae0/build/haproxy/Dockerfile#L3
https://github.com/conjurdemos/cdemo/blob/78c34ca280a71bd0223831d7b81c9eb25ed78ae0/build/haproxy/Dockerfile#L4
https://github.com/conjurdemos/cdemo/blob/78c34ca280a71bd0223831d7b81c9eb25ed78ae0/build/haproxy/Dockerfile#L5

Splitting `apt-get update` and `apt-get install -y ...` will cause caching issues when building and can cause file sizes to be larger than necessary.

Combine all 3 RUN commands L3-L5 into one RUN command instead:

```Dockerfile
RUN apt-get clean \
 && apt-get update \
 && apt-get install -y \
        curl \
        git
```

**Comment by infamousjoeg** [comment]
I would actually add `&& rm -rf /var/lib/apt/lists/*` to the end to further reduce file size.

**Comment by jodyhuntatx** [comment]
done - should probably check other dockerfiles for such things.
