### ISSUE TITLE
dependencies setup issue on centos 7

### ISSUE THREAD

**Issue by kohawk41** [conjurdemos/cdemo#18]
dependencies are not completing when running as root on centos 7. Docker is installed, but not started. I had to manually install jq, conjur cli, etc after line 24 in the dependencies script. here is the output

./_install-dependencies.sh: line 24: /etc/docker/daemon.json: No such file or directory

Installed:
  docker-ce.x86_64 0:17.12.0.ce-1.el7.centos

Dependency Installed:
  audit-libs-python.x86_64 0:2.7.6-3.el7                        checkpolicy.x86_64 0:2.5-4.el7
  container-selinux.noarch 2:2.33-1.git86f33cd.el7              libcgroup.x86_64 0:0.41-13.el7
  libseccomp.x86_64 0:2.3.1-3.el7                               libsemanage-python.x86_64 0:2.5-8.el7
  policycoreutils-python.x86_64 0:2.5-17.1.el7                  python-IPy.noarch 0:0.75-6.el7
  setools-libs.x86_64 0:3.3.8-1.1.el7

Complete!
./_install-dependencies.sh: line 24: /etc/docker/daemon.json: No such file or directory

**Comment by jodyhuntatx** [comment]
good catch. that was added to fix an issue that showed up in Skytap. It shouldn't affect running on Centos7. I'll add a line to create the file and make sure it's writable first.

**Comment by jodyhuntatx** [comment]
meaning you should be able to delete it or comment it out and everything should work.

**Comment by dataplex** [comment]
Pull request #20 should resolve this issue.

**Comment by kohawk41** [comment]
Thanks guys!
