### ISSUE TITLE
CONJUR_CONTAINER_TARFILE in docker-compose.yml

### ISSUE THREAD

**Issue by infamousjoeg** [conjurdemos/cdemo#2]
In [README.md](README.md), there is no mention of the necessity for a Conjur Appliance TAR file, nor mention of editing [docker-compose.yml](docker-compose.yml) for the path to the TAR file until after initially running `$ ./0-startup-conjur.sh` and receiving a nag error.

Please update [README.md](README.md) to reflect these pre-requisites to configuration prior to execution of the shell script.

**Comment by jodyhuntatx** [comment]
good feedback. done
