### ISSUE TITLE
/usr/local/bin not available to sudo - causes "docker-compose" commands to fail

### ISSUE THREAD

**Issue by kazekan** [conjurdemos/cdemo#29]
Without making specific modifications to the global PATH, sudoers "secure_path" or other potential solutions, the docker-compose commands will fail when running scripts with sudo since /usr/local/bin is not a path sudo is aware of. It would be helpful for those of us less familiar with Unix/Linux to have this resolved as part of the dependency installation process to avoid multiple people having to troubleshoot on their own.

Thanks!

**Comment by jodyhuntatx** [comment]
fixed in v5-merge branch.
