### ISSUE TITLE
Add SUDO requirement to README.md for non-privileged users

### ISSUE THREAD

**Issue by infamousjoeg** [conjurdemos/cdemo#57]
I've run into many problems when not preceding commands on the README.md with `sudo` as a non-privileged user.  Adding a note explaining this requirement or utilizing `become` within the roles/playbooks would be helpful.

**Comment by ryanprior** [comment]
This is addressed with the recently merged `bin/install` and `bin/install-ansible` scripts which do `sudo` for you when necessary.
