### ISSUE TITLE
All Jenkins Pipelines Broken

### ISSUE THREAD

**Issue by magicmarkh-zz** [conjurdemos/cdemo#77]
after a successful setup, all jenkins jobs fail with the error:

 java.lang.NoSuchMethodError: No such DSL method 'pipeline' found among steps [acceptGitLabMR, addGitLabMRComment, archive, build, catchError, checkout, deleteDir, dir, echo, emailext, emailextrecipients, error, fileExists, getContext, git, gitlabBuilds, gitlabCommitStatus, input, isUnix, jiraComment, jiraIssueSelector, jiraSearch, junit, library, libraryResource, load, lock, mail, milestone, parallel, properties, publishHTML, pwd, readFile, readTrusted, resolveScm, retry, sleep, stage, stash, step, svn, timeout, timestamps, tm, tool, unarchive, unstash, updateGitlabCommitStatus, waitUntil, withContext, withCredentials, withEnv, wrap, writeFile] or symbols [all, always, ant, antFromApache, antOutcome, antPath, antTarget, apiToken, architecture, archiveArtifacts, artifactManager, authorizationMatrix, batchFile, bitbucket, booleanParam, brokenBuildSuspects, brokenTestsSuspects, buildButton, buildDiscarder, caseInsensitive, caseSensitive, certificate, choice, choiceParam, clock, cloud, cobertura, coberturaAdapter, command, configFile, configFileProvider, credentials, cron, crumb, culprits, defaultView, demand, developers, disableConcurrentBuilds, disableResume, dockerCert, downloadSettings, downstream, dumb, durabilityHint, envVars, file, fileParam, filePath, fingerprint, frameOptions, freeStyle, freeStyleJob, fromScm, fromSource, git, gitBranchDiscovery, gitLabConnection, gitTagDiscovery, github, githubPush, gitlab, globalConfigFiles, headRegexFilter, headWildcardFilter, hyperlink, hyperlinkToModels, inheriting, inheritingGlobal, installSource, istanbulCobertura, istanbulCoberturaAdapter, jacoco, jacocoAdapter, jdk, jgit, jgitapache, jnlp, jobName, lastDuration, lastFailure, lastGrantedAuthorities, lastStable, lastSuccess, legacy, legacySCM, list, local, location, logRotator, loggedInUsersCanDoAnything, masterBuild, maven, maven3Mojos, mavenErrors, mavenMojos, mavenWarnings, modernSCM, myView, nodeProperties, nonInheriting, nonStoredPasswordParam, none, overrideIndexTriggers, paneStatus, parameters, password, pattern, permanent, pipelineTriggers, plainText, plugin, pollSCM, projectNamingStrategy, proxy, publishCoverage, queueItemAuthenticator, quietPeriod, rateLimitBuilds, recipients, remotingCLI, requestor, run, runParam, schedule, scmRetryCount, scriptApprovalLink, search, security, shell, slave, sourceFiles, sourceRegexFilter, sourceWildcardFilter, sshUserPrivateKey, stackTrace, standard, status, string, stringParam, swapSpace, text, textParam, tmpSpace, toolLocation, unsecured, upstream, upstreamDevelopers, usernameColonPassword, usernamePassword, viewsTabBar, weather, withAnt, zfs, zip] or globals [currentBuild, env, params, scm]

**Comment by ryanprior** [comment]
Thank you for the report @TopHatCyberLabs, I'll take a look at the Jenkins jobs & get back to you.

**Comment by ryanprior** [comment]
This should be fixed in the just-released cdemo 1.3.1, please let me know if you have any further issues and thank you again for reporting!
